version: '3.9'

services:
  database:
    image: "postgres:latest"
    restart: always
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '54320:5432'